export const FETCH_ITINERARY_REQUEST = 'FETCH_ITINERARY_REQUEST';
export const FETCH_ITINERARY_SUCCESS = 'FETCH_ITINERARY_SUCCESS';
export const FETCH_ITINERARY_FAILURE = 'FETCH_ITINERARY_FAILURE';
export const SET_ITINERARY_FIELD = 'SET_ITINERARY_FIELD';
export const RESET_ITINERARY_FORM = 'RESET_ITINERARY_FORM';
